/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.PI2.view;

import POJO.Aluno;
import POJO.AlunoRepository;
import javax.swing.JOptionPane;

/**
 *
 * @author jvazu
 */
public class AtribuirNotaView extends javax.swing.JFrame {
    private static String codigoMatricula;
    /**
     * Creates new form AtribuirNotaView
     * 
     * 
     */
    
    public AtribuirNotaView(String codigoMatricula) {
    this.codigoMatricula = codigoMatricula;
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldMatematica = new javax.swing.JTextField();
        jTextFieldPortugues = new javax.swing.JTextField();
        jTextFieldCiencias = new javax.swing.JTextField();
        jTextFieldHistoria = new javax.swing.JTextField();
        jLabelMatematica = new javax.swing.JLabel();
        jLabelPortugues = new javax.swing.JLabel();
        jLabelCiencias = new javax.swing.JLabel();
        jLabelHistoria = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonConcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMatematica.setText("Matemática:");

        jLabelPortugues.setText("Português:");

        jLabelCiencias.setText("Ciências:");

        jLabelHistoria.setText("História:");

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Atribua as notas do aluno");

        jButtonConcluir.setText("Atribuir Notas");
        jButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatematica, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPortugues, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCiencias, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHistoria, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMatematica)
                            .addComponent(jTextFieldPortugues)
                            .addComponent(jTextFieldCiencias)
                            .addComponent(jTextFieldHistoria))
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMatematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMatematica))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPortugues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPortugues))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCiencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCiencias))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHistoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirActionPerformed
        // Obter as notas digitadas nos campos de texto
        float notaMatematica = Float.parseFloat(jTextFieldMatematica.getText());
        float notaPortugues = Float.parseFloat(jTextFieldPortugues.getText());
        float notaCiencias = Float.parseFloat(jTextFieldCiencias.getText());
        float notaHistoria = Float.parseFloat(jTextFieldHistoria.getText());
        
        // Atualizar as notas do aluno correspondente ao código de matrícula
        AlunoRepository alunoRepository = new AlunoRepository();
        Aluno aluno = alunoRepository.buscarAlunoPorCodigoMatricula(codigoMatricula);
        
        if (aluno != null) {
        aluno.setNotaMatematica(notaMatematica);
        aluno.setNotaPortugues(notaPortugues);
        aluno.setNotaCiencias(notaCiencias);
        aluno.setNotaHistoria(notaHistoria);
        
        // Salvar as notas atualizadas
        alunoRepository.atualizarAluno(aluno);
        
        // Exibir uma mensagem de sucesso
        JOptionPane.showMessageDialog(this, "Notas atribuídas com sucesso.");
        
        // Fechar a janela após concluir
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Aluno não encontrado.");
    }
    }//GEN-LAST:event_jButtonConcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtribuirNotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtribuirNotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtribuirNotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtribuirNotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtribuirNotaView(codigoMatricula).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConcluir;
    private javax.swing.JLabel jLabelCiencias;
    private javax.swing.JLabel jLabelHistoria;
    private javax.swing.JLabel jLabelMatematica;
    private javax.swing.JLabel jLabelPortugues;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCiencias;
    private javax.swing.JTextField jTextFieldHistoria;
    private javax.swing.JTextField jTextFieldMatematica;
    private javax.swing.JTextField jTextFieldPortugues;
    // End of variables declaration//GEN-END:variables

}
