/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.PI2.view;

import POJO.Aluno;
import POJO.AlunoRepository;
import br.com.PI2.view.AtribuirNotaView;
import br.com.PI2.view.HomeView;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.String;

/**
 *
 * @author jvazu
 */
public class HistoricoEscolarView extends javax.swing.JFrame {
    
    private AlunoRepository alunoRepository = new AlunoRepository();
    private String codigoMatricula = "";
    /**
     * Creates new form HistoricoEscolarView
     */
    public HistoricoEscolarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldMatriculaAluno = new javax.swing.JTextField();
        jLabelDigite = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabela = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonAtribuirNota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Histórico Escolar");

        jLabelDigite.setText("Digite o código de matrícula do aluno que deseja selecionar:");

        jTableTabela.setModel(criarTabela(codigoMatricula));
        jScrollPane1.setViewportView(jTableTabela);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar ao menu");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonAtribuirNota.setText("Atribuir nota");
        jButtonAtribuirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtribuirNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDigite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar)
                        .addContainerGap(291, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar)
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAtribuirNota)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButtonVoltar)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDigite)
                    .addComponent(jButtonBuscar))
                .addGap(32, 32, 32)
                .addComponent(jButtonAtribuirNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String codigoMatricula = jTextFieldMatriculaAluno.getText();
        Aluno aluno = alunoRepository.buscarAlunoPorCodigoMatricula(codigoMatricula);

        if (aluno != null) {
            // Preencher a tabela com as notas do aluno
            jTableTabela.setModel(criarTabela(codigoMatricula));
        } else {
            JOptionPane.showMessageDialog(this, "Aluno não encontrado.");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed
   
    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.dispose();
        HomeView homeView = new HomeView();
        homeView.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAtribuirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtribuirNotaActionPerformed
        // Obtém o código de matrícula do aluno do jTextFieldMatriculaAluno
        String codigoMatricula = jTextFieldMatriculaAluno.getText();

        // Verifica se o código de matrícula não está vazio
        if (!codigoMatricula.isEmpty()) {
            // Abre a AtribuirNotaView passando o código de matrícula do aluno
            AtribuirNotaView atribuirNotaView = new AtribuirNotaView(codigoMatricula);
            atribuirNotaView.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, insira um código de matrícula válido.");
        }
    }//GEN-LAST:event_jButtonAtribuirNotaActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTableTabela.setModel(criarTabela(codigoMatricula));
        jScrollPane1.setViewportView(jTableTabela);
        jScrollPane1.revalidate();                                    
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoEscolarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoEscolarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoEscolarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoEscolarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoEscolarView().setVisible(true);
            }
        });
    }
    public DefaultTableModel criarTabela(String codigoMatricula) {
        Aluno aluno = alunoRepository.buscarAlunoPorCodigoMatricula(codigoMatricula);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Disciplina");
        model.addColumn("Nota");

        if (aluno != null) {
        // Adiciona as notas do aluno ao modelo de tabela
        model.addRow(new Object[]{"Matemática", aluno.getNotaMatematica()});
        model.addRow(new Object[]{"Português", aluno.getNotaPortugues()});
        model.addRow(new Object[]{"Ciências", aluno.getNotaCiencias()});
        model.addRow(new Object[]{"História", aluno.getNotaHistoria()});
        } else {
        // Se o aluno não for encontrado, adiciona linhas vazias
        model.addRow(new Object[]{"Matemática", ""});
        model.addRow(new Object[]{"Português", ""});
        model.addRow(new Object[]{"Ciências", ""});
        model.addRow(new Object[]{"História", ""});
        }

    return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtribuirNota;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDigite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabela;
    private javax.swing.JTextField jTextFieldMatriculaAluno;
    // End of variables declaration//GEN-END:variables
}
